/* Generated By:JavaCC: Do not edit this line. PaymentParserConstants.java */
package fhv.ws22.se.skyward.domain.paymentParser;


/** 
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PaymentParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int EQ = 5;
  /** RegularExpression Id. */
  int RES = 6;
  /** RegularExpression Id. */
  int DATE = 7;
  /** RegularExpression Id. */
  int AMOUNT = 8;
  /** RegularExpression Id. */
  int IBAN = 9;
  /** RegularExpression Id. */
  int SEPERATOR = 10;
  /** RegularExpression Id. */
  int MONTH = 11;
  /** RegularExpression Id. */
  int NUMBER = 12;
  /** RegularExpression Id. */
  int FLOAT = 13;
  /** RegularExpression Id. */
  int DATE_TYPE = 14;
  /** RegularExpression Id. */
  int IBAN_TYPE = 15;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\n\"",
    "\"=\"",
    "\"Res#\"",
    "\"Date\"",
    "\"Amount\"",
    "\"IBAN\"",
    "\";\"",
    "<MONTH>",
    "<NUMBER>",
    "<FLOAT>",
    "<DATE_TYPE>",
    "<IBAN_TYPE>",
    "\"#\"",
  };

}
